export type ColumnDef = {
  key: string;
  header: string;
  width: number;
  required?: boolean;
  hint?: string;
};

export type TemplateDef = {
  key: string;
  title: string;
  filename: string;
  desc: string;
  sheetName: string;
  tabColor: string;
  columns: ColumnDef[];
  samples: Record<string, string | number>[];
  instructions: string[];
  target: string;
};

export const TEMPLATES: Record<string, TemplateDef> = {
  mehsul: {
    key: "mehsul",
    title: "Məhsul kataloqu",
    filename: "360biznes_mehsul_sablon.xlsx",
    desc: "Məhsul adı, barkod, qiymət tipləri, ilkin stok",
    sheetName: "Məhsullar",
    tabColor: "FF6366F1",
    target: "mehsullar + stok + mehsul_barkodlar",
    columns: [
      { key: "ad", header: "Məhsul adı", width: 36, required: true },
      { key: "kod", header: "Kod (SKU)", width: 16 },
      { key: "barkod", header: "Barkod", width: 18, hint: "Çoxlu barkod | ilə ayır" },
      { key: "marka", header: "Marka", width: 18 },
      { key: "model", header: "Model", width: 18 },
      { key: "kateqoriya", header: "Kateqoriya", width: 22 },
      { key: "alt_kateqoriya", header: "Alt kateqoriya", width: 22 },
      { key: "vahid", header: "Ölçü vahidi", width: 12, hint: "əd, kq, m, litr" },
      { key: "anbar", header: "Anbar", width: 18, hint: "Boş = əsas anbar" },
      { key: "alish_qiymeti", header: "Maya qiyməti", width: 14 },
      { key: "satis_qiymeti", header: "Pərakəndə qiymət", width: 16, required: true },
      { key: "topdan_qiymeti", header: "Topdan qiymət", width: 16 },
      { key: "partnyor_qiymeti", header: "Partnyor qiymət", width: 16 },
      { key: "vip_qiymeti", header: "VIP qiymət", width: 14 },
      { key: "say", header: "İlkin stok", width: 12, required: true },
      { key: "kritik_stok", header: "Min stok (xəbər)", width: 16 },
      { key: "vergi", header: "Vergi %", width: 10 },
      { key: "sekil_url", header: "Şəkil URL (vergüllə)", width: 50, hint: "https://..." },
      { key: "tesvir", header: "Təsvir", width: 50 },
      { key: "aktiv", header: "Aktiv (1/0)", width: 10 },
    ],
    samples: [
      {
        ad: "iPhone 15 Pro 256GB",
        kod: "IPH15PRO-256",
        barkod: "1234567890123",
        marka: "Apple",
        model: "iPhone 15 Pro",
        kateqoriya: "Telefonlar",
        alt_kateqoriya: "iPhone",
        vahid: "əd",
        anbar: "",
        alish_qiymeti: 2500,
        satis_qiymeti: 2890,
        topdan_qiymeti: 2750,
        partnyor_qiymeti: 2700,
        vip_qiymeti: 2800,
        say: 12,
        kritik_stok: 3,
        vergi: 18,
        sekil_url: "https://example.com/iphone15.jpg",
        tesvir: "Apple A17 Pro çip, 256GB",
        aktiv: 1,
      },
    ],
    instructions: [
      "Eyni kod və ya barkodda məhsul varsa yenilənir (yeni yaradılmır)",
      "İlkin stok boş qoy → 0 alınır",
      "Şəkil URL avto endirilir və CDN-ə yüklənir",
      "Çoxlu barkod | (pipe) ilə ayır: 123|456|789",
      "Vahid boş = «əd» götürülür",
    ],
  },

  musteri: {
    key: "musteri",
    title: "Müştərilər",
    filename: "360biznes_musteri_sablon.xlsx",
    desc: "Müştəri kataloqu və ilkin borc qalığı",
    sheetName: "Müştərilər",
    tabColor: "FF0EA5E9",
    target: "kontragentler (nov='musteri')",
    columns: [
      { key: "ad", header: "Ad/Şirkət adı", width: 30, required: true },
      { key: "tip", header: "Tip (sahib/sirket)", width: 16, hint: "Boş = sahib" },
      { key: "voen", header: "VÖEN", width: 14 },
      { key: "telefon", header: "Telefon", width: 18 },
      { key: "email", header: "Email", width: 24 },
      { key: "seh_r", header: "Şəhər", width: 16 },
      { key: "unvan", header: "Ünvan", width: 36 },
      { key: "qiymet_tipi", header: "Qiymət tipi", width: 16, hint: "adi/topdan/vip" },
      { key: "endirim", header: "Endirim %", width: 12 },
      { key: "borc_limit", header: "Borc limiti (₼)", width: 16 },
      { key: "borc", header: "İlkin borc qalığı (₼)", width: 20, hint: "Müsbət = müştəri sizə borclu" },
      { key: "qeyd", header: "Qeyd", width: 40 },
      { key: "aktiv", header: "Aktiv (1/0)", width: 10 },
    ],
    samples: [
      {
        ad: "Əliyev Vüsal",
        tip: "sahib",
        voen: "",
        telefon: "+994501234567",
        email: "vusal@example.com",
        seh_r: "Bakı",
        unvan: "Nəsimi ray., Bül-Bül 24",
        qiymet_tipi: "adi",
        endirim: 0,
        borc_limit: 1000,
        borc: 250,
        qeyd: "Köhnə müştəri",
        aktiv: 1,
      },
    ],
    instructions: [
      "Telefon formatı: +994501234567 və ya 0501234567",
      "Eyni telefon və ya VÖEN-də müştəri varsa yenilənir",
      "İlkin borc müsbət rəqəmdir — müştərinin sizə borcunu göstərir",
      "Qiymət tipi boş = «adi» (pərakəndə)",
    ],
  },

  techizatci: {
    key: "techizatci",
    title: "Təchizatçılar",
    filename: "360biznes_techizatci_sablon.xlsx",
    desc: "Təchizatçı kataloqu və kreditor qalığı",
    sheetName: "Təchizatçılar",
    tabColor: "FFF59E0B",
    target: "kontragentler (nov='techizatci')",
    columns: [
      { key: "ad", header: "Şirkət adı", width: 30, required: true },
      { key: "voen", header: "VÖEN", width: 14 },
      { key: "direktor", header: "Direktor", width: 22 },
      { key: "telefon", header: "Telefon", width: 18 },
      { key: "email", header: "Email", width: 24 },
      { key: "unvan", header: "Ünvan", width: 36 },
      { key: "bank_adi", header: "Bank adı", width: 22 },
      { key: "iban", header: "IBAN", width: 32 },
      { key: "odenis_gun", header: "Ödəniş müddəti (gün)", width: 18 },
      { key: "borc", header: "İlkin borc (₼)", width: 16, hint: "Sizin təchizatçıya borcunuz" },
      { key: "aktiv", header: "Aktiv (1/0)", width: 10 },
    ],
    samples: [
      {
        ad: "AzerTechno MMC",
        voen: "1234567890",
        direktor: "Qurban Quliyev",
        telefon: "+994122345678",
        email: "info@aztechno.az",
        unvan: "Bakı ş., Yasamal r.",
        bank_adi: "Kapital Bank",
        iban: "AZ77NABZ01350000000000001944",
        odenis_gun: 30,
        borc: 1500,
        aktiv: 1,
      },
    ],
    instructions: [
      "IBAN avto köçürmə üçün istifadə olunur",
      "İlkin borc = sizin təchizatçıya borcunuz (müsbət rəqəm)",
      "Eyni VÖEN-də təchizatçı varsa yenilənir",
    ],
  },

  "kassa-baslangic": {
    key: "kassa-baslangic",
    title: "Kassa/Bank ilkin balansı",
    filename: "360biznes_hesab_sablon.xlsx",
    desc: "Hər hesab üçün açılış balansı",
    sheetName: "Hesablar",
    tabColor: "FF06B6D4",
    target: "maliye_hesablari",
    columns: [
      { key: "ad", header: "Hesab adı", width: 30, required: true },
      { key: "nov", header: "Növ", width: 14, required: true, hint: "negd / bank / kart" },
      { key: "bank_adi", header: "Bank", width: 22 },
      { key: "iban", header: "IBAN", width: 32 },
      { key: "kart_son4", header: "Kart son 4", width: 12 },
      { key: "valyuta", header: "Valyuta", width: 10, hint: "AZN/USD/EUR" },
      { key: "qaliq", header: "İlkin balans (₼)", width: 18, required: true },
      { key: "qeyd", header: "Qeyd", width: 36 },
    ],
    samples: [
      { ad: "Əsas kassa", nov: "negd", bank_adi: "", iban: "", kart_son4: "", valyuta: "AZN", qaliq: 500, qeyd: "Mağaza kassası" },
      { ad: "Kapital Hesab", nov: "bank", bank_adi: "Kapital Bank", iban: "AZ77NABZ01350000000000001944", kart_son4: "", valyuta: "AZN", qaliq: 12500, qeyd: "Əsas bank hesabı" },
    ],
    instructions: [
      "Növ: negd (nağd kassa), bank (cari hesab), kart (kart hesabı)",
      "Bank və kart üçün IBAN tövsiyə olunur",
      "Eyni adda hesab varsa yenilənir",
    ],
  },

  alis: {
    key: "alis",
    title: "Alış tarixçəsi",
    filename: "360biznes_alis_sablon.xlsx",
    desc: "Köhnə alış qaimələri (qaimə + sətirlər)",
    sheetName: "Alışlar",
    tabColor: "FF10B981",
    target: "alis_sifarisleri + alis_sifaris_satirlari",
    columns: [
      { key: "qaime_no", header: "Qaimə №", width: 14 },
      { key: "tarix", header: "Tarix", width: 14, required: true, hint: "YYYY-MM-DD" },
      { key: "techizatci", header: "Təchizatçı (ad və ya VÖEN)", width: 28, required: true },
      { key: "anbar", header: "Anbar", width: 18 },
      { key: "valyuta", header: "Valyuta", width: 10 },
      { key: "endirim", header: "Endirim (₼)", width: 14 },
      { key: "vergi", header: "Vergi (₼)", width: 14 },
      { key: "dasima", header: "Daşıma (₼)", width: 14 },
      { key: "status", header: "Status", width: 14, hint: "odenildi/aciq" },
      { key: "mehsul_kod", header: "Məhsul kodu/barkod", width: 22, required: true },
      { key: "miqdar", header: "Miqdar", width: 12, required: true },
      { key: "maya", header: "Maya qiymət", width: 14, required: true },
      { key: "qeyd", header: "Qeyd", width: 30 },
    ],
    samples: [
      { qaime_no: "AL-001", tarix: "2025-12-01", techizatci: "AzerTechno MMC", anbar: "", valyuta: "AZN", endirim: 0, vergi: 0, dasima: 50, status: "odenildi", mehsul_kod: "IPH15PRO-256", miqdar: 5, maya: 2500, qeyd: "" },
      { qaime_no: "AL-001", tarix: "2025-12-01", techizatci: "AzerTechno MMC", anbar: "", valyuta: "AZN", endirim: 0, vergi: 0, dasima: 0, status: "odenildi", mehsul_kod: "IPH15PRO-128", miqdar: 3, maya: 2100, qeyd: "" },
    ],
    instructions: [
      "Hər sətr = bir məhsul. Eyni Qaimə № avto qruplaşır",
      "Tarix formatı: 2025-12-01 (YYYY-MM-DD)",
      "Status: odenildi/aciq/legv",
      "Məhsul yoxdursa avto yaradılır (kod ilə)",
    ],
  },

  satis: {
    key: "satis",
    title: "Satış tarixçəsi",
    filename: "360biznes_satis_sablon.xlsx",
    desc: "Köhnə satış qaimələri",
    sheetName: "Satışlar",
    tabColor: "FFEF4444",
    target: "satis_sifarisleri + satis_sifaris_satirlari",
    columns: [
      { key: "qaime_no", header: "Qaimə №", width: 14 },
      { key: "tarix", header: "Tarix", width: 14, required: true },
      { key: "musteri", header: "Müştəri (ad/telefon)", width: 24 },
      { key: "satici", header: "Satıcı (email)", width: 22 },
      { key: "filial", header: "Filial", width: 18 },
      { key: "anbar", header: "Anbar", width: 18 },
      { key: "odenis", header: "Ödəniş növü", width: 16, hint: "negd/kart/koc/borc" },
      { key: "endirim", header: "Endirim", width: 12 },
      { key: "status", header: "Status", width: 14 },
      { key: "mehsul_kod", header: "Məhsul kodu/barkod", width: 22, required: true },
      { key: "miqdar", header: "Miqdar", width: 12, required: true },
      { key: "qiymet", header: "Satış qiyməti", width: 14, required: true },
      { key: "vergi", header: "Vergi", width: 12 },
      { key: "qeyd", header: "Qeyd", width: 30 },
    ],
    samples: [
      { qaime_no: "ST-001", tarix: "2025-12-15", musteri: "+994501234567", satici: "satici@firma.az", filial: "Baş ofis", anbar: "", odenis: "kart", endirim: 0, status: "tesdiq", mehsul_kod: "IPH15PRO-256", miqdar: 1, qiymet: 2890, vergi: 0, qeyd: "" },
    ],
    instructions: [
      "Status: tesdiq/legv/qaytarma",
      "Müştəri yoxdursa avto yaradılır",
      "Stok avtomatik azaldılır",
    ],
  },

  servis: {
    key: "servis",
    title: "Servis qeydləri",
    filename: "360biznes_servis_sablon.xlsx",
    desc: "Servis sifarişləri tarixçəsi",
    sheetName: "Servis",
    tabColor: "FF8B5CF6",
    target: "servis_qebullar + servis_isleri",
    columns: [
      { key: "qebul_no", header: "Qəbul №", width: 14 },
      { key: "qebul_tarix", header: "Qəbul tarixi", width: 14, required: true },
      { key: "musteri", header: "Müştəri", width: 24, required: true },
      { key: "telefon", header: "Telefon", width: 18 },
      { key: "mehsul", header: "Məhsul", width: 28 },
      { key: "seriya", header: "Seriya/IMEI", width: 22 },
      { key: "komplekt", header: "Komplekt", width: 20 },
      { key: "sikayet", header: "Şikayət/problem", width: 40 },
      { key: "diaqnoz", header: "Diaqnoz", width: 30 },
      { key: "status", header: "Status", width: 16 },
      { key: "texnik", header: "Texnik", width: 22 },
      { key: "mebleg", header: "İlkin məbləğ", width: 14 },
      { key: "yekun_mebleg", header: "Yekun məbləğ", width: 14 },
      { key: "zemanet", header: "Zəmanət (gün)", width: 14 },
      { key: "tehvil_tarix", header: "Təhvil tarixi", width: 14 },
      { key: "qeyd", header: "Qeyd", width: 30 },
    ],
    samples: [
      {
        qebul_no: "SRV-001",
        qebul_tarix: "2025-11-20",
        musteri: "Aliyev Rauf",
        telefon: "+994551112233",
        mehsul: "iPhone 13 Pro",
        seriya: "356789012345678",
        komplekt: "Tək telefon",
        sikayet: "Ekran qara",
        diaqnoz: "LCD dəyişəcək",
        status: "hazir",
        texnik: "Elvin",
        mebleg: 50,
        yekun_mebleg: 180,
        zemanet: 30,
        tehvil_tarix: "2025-11-22",
        qeyd: "",
      },
    ],
    instructions: [
      "Status: qebul/yoxlanir/hazir/tehvil/legv",
      "IMEI ilə məhsul kataloquna bağlanır (varsa)",
      "Yekun məbləğ boş = ilkin məbləğdən götürülür",
    ],
  },

  emekdas: {
    key: "emekdas",
    title: "Əməkdaşlar",
    filename: "360biznes_emekdas_sablon.xlsx",
    desc: "İşçi kataloqu + maaş + IBAN",
    sheetName: "Əməkdaşlar",
    tabColor: "FF14B8A6",
    target: "istifadeciler",
    columns: [
      { key: "ad_soyad", header: "Ad Soyad", width: 30, required: true },
      { key: "isci_kod", header: "İşçi kodu", width: 14 },
      { key: "email", header: "Email", width: 24, required: true },
      { key: "telefon", header: "Telefon", width: 18 },
      { key: "vezife", header: "Vəzifə", width: 22 },
      { key: "sobe", header: "Şöbə", width: 18 },
      { key: "fin", header: "FİN kod", width: 12 },
      { key: "dogum", header: "Doğum tarixi", width: 14 },
      { key: "ise_qebul", header: "İşə qəbul tarixi", width: 16, required: true },
      { key: "maas", header: "Maaş (₼)", width: 12 },
      { key: "maas_tipi", header: "Maaş tipi", width: 12, hint: "ayliq/saatliq" },
      { key: "kpi", header: "KPI %", width: 10 },
      { key: "iban", header: "IBAN", width: 32 },
      { key: "unvan", header: "Ünvan", width: 30 },
      { key: "qohum_tel", header: "Qohum telefon", width: 18 },
      { key: "aktiv", header: "Aktiv (1/0)", width: 10 },
    ],
    samples: [
      {
        ad_soyad: "Məmmədov Elvin",
        isci_kod: "EMP-001",
        email: "elvin@firma.az",
        telefon: "+994501112233",
        vezife: "Satıcı",
        sobe: "Satış",
        fin: "1ABCDEF",
        dogum: "1995-05-10",
        ise_qebul: "2024-03-01",
        maas: 800,
        maas_tipi: "ayliq",
        kpi: 5,
        iban: "AZ77NABZ01350000000000001944",
        unvan: "Bakı",
        qohum_tel: "+994551112233",
        aktiv: 1,
      },
    ],
    instructions: [
      "Email unikal olmalıdır — eyni email = mövcud işçi yenilənir",
      "Yeni işçi üçün avto-default şifrə yaradılır (məcburi dəyiş)",
      "Maaş tipi: ayliq/saatliq",
    ],
  },

  crm: {
    key: "crm",
    title: "CRM / Leadlər",
    filename: "360biznes_crm_sablon.xlsx",
    desc: "Potensial müştərilər və lead-lər",
    sheetName: "CRM",
    tabColor: "FFD946EF",
    target: "kontragentler (funnel_status)",
    columns: [
      { key: "ad", header: "Ad", width: 30, required: true },
      { key: "qaynaq", header: "Mənbə", width: 18, hint: "reklam/tovsiye/sayt/sosial" },
      { key: "kampaniya", header: "Kampaniya", width: 22 },
      { key: "telefon", header: "Telefon", width: 18 },
      { key: "email", header: "Email", width: 24 },
      { key: "maraq", header: "Maraqlandığı məhsul", width: 28 },
      { key: "funnel_status", header: "Status", width: 16, hint: "yeni/elaqe/teklif/ugur/itki" },
      { key: "menecer", header: "Cavabdeh menecer (email)", width: 24 },
      { key: "novbeti_elaqe", header: "Növbəti əlaqə tarixi", width: 18 },
      { key: "qeyd", header: "Qeyd", width: 40 },
      { key: "etiket", header: "Etiketlər (vergüllə)", width: 24 },
    ],
    samples: [
      {
        ad: "Hüseynov Tural",
        qaynaq: "reklam",
        kampaniya: "Yaz endirim 2026",
        telefon: "+994551234567",
        email: "tural@gmail.com",
        maraq: "MacBook Pro M3",
        funnel_status: "elaqe",
        menecer: "satici@firma.az",
        novbeti_elaqe: "2026-05-20",
        qeyd: "Biznes üçün almaq istəyir",
        etiket: "premium,b2b",
      },
    ],
    instructions: [
      "Status: yeni/elaqe/teklif/ugur/itki",
      "Eyni telefonda lead varsa yenilənir",
    ],
  },

  stok: {
    key: "stok",
    title: "Stok cədvəli (sayım)",
    filename: "360biznes_stok_sablon.xlsx",
    desc: "Anbar sayımı — məhsul + miqdar + maya",
    sheetName: "Stok",
    tabColor: "FFEA580C",
    target: "stok + anbar_hereketleri",
    columns: [
      { key: "mehsul_kod", header: "Məhsul kodu/barkod", width: 22, required: true },
      { key: "anbar", header: "Anbar adı", width: 22, required: true },
      { key: "miqdar", header: "Miqdar", width: 12, required: true },
      { key: "maya", header: "Maya qiyməti", width: 14 },
      { key: "veziyyet", header: "Vəziyyət", width: 14, hint: "yeni/islenmis" },
      { key: "tarix", header: "Tarix", width: 14 },
      { key: "qeyd", header: "Qeyd", width: 30 },
    ],
    samples: [
      { mehsul_kod: "IPH15PRO-256", anbar: "Əsas anbar", miqdar: 12, maya: 2500, veziyyet: "yeni", tarix: "2026-05-14", qeyd: "" },
    ],
    instructions: [
      "Məhsul kodu ilə tapılır, yoxdursa xəta",
      "Mövcud stok bu sayımla əvəzlənir (set olunur, artırılmır)",
      "Anbar yoxdursa xəta",
    ],
  },
};

// kassa-baslangic — hesab/kassa açılış balansı
TEMPLATES["kassa-baslangic"] = {
  key: "kassa-baslangic",
  title: "Kassa / hesab başlanğıc balansı",
  filename: "360biznes_kassa_baslangic_sablon.xlsx",
  desc: "Kassa, bank hesabları və ilkin balanslar",
  sheetName: "Hesablar",
  tabColor: "FF06B6D4",
  target: "maliye_hesablari",
  columns: [
    { key: "ad", header: "Hesab adı", width: 28, required: true, hint: "Mərkəzi kassa, ABB cari hesab və s." },
    { key: "nov", header: "Növ", width: 14, required: true, hint: "negd / bank / kart" },
    { key: "valyuta", header: "Valyuta", width: 10, hint: "AZN (default), USD, EUR" },
    { key: "qaliq", header: "İlkin balans", width: 16, required: true },
    { key: "bank_adi", header: "Bank adı", width: 22, hint: "Yalnız bank/kart üçün" },
    { key: "hesab_nomresi", header: "Hesab nömrəsi / IBAN", width: 32 },
    { key: "qeyd", header: "Qeyd", width: 30 },
  ],
  samples: [
    { ad: "Mərkəzi kassa", nov: "negd", valyuta: "AZN", qaliq: 5000, qeyd: "Açılış balansı" },
    { ad: "ABB cari hesab", nov: "bank", valyuta: "AZN", qaliq: 25000, bank_adi: "ABB", hesab_nomresi: "AZ21NABZ00000000000123456789" },
  ],
  instructions: [
    "Mövcud hesab adı varsa balans yenilənir",
    "Yeni hesab yaradılır, ilkin balans daxili maliyyə əməliyyatı kimi yazılır",
    "Növ: negd / bank / kart (lowercase)",
  ],
};

export const TEMPLATE_KEYS = Object.keys(TEMPLATES);

export function getTemplate(key: string): TemplateDef | null {
  return TEMPLATES[key] ?? null;
}
