import type { LucideIcon } from "lucide-react";
import {
  Coins, Workflow, Bell, UserCircle, Target, Briefcase, Boxes, Bot, Plug,
  LineChart, ShieldCheck, KeyRound, CalendarClock, Trophy, Award,
  Mic, ScanLine, Calculator, Languages, ShieldAlert, BarChart3,
  Camera, Mail, MessageSquare,
  Cake, ShoppingBag, UserPlus, Star, Ticket, ArrowUpRight,
  CloudSun, Megaphone, TrendingUp,
  CalendarDays, AlertTriangle, Radar, Truck, Wallet, FileText,
  MessageCircle, DollarSign, Gavel,
  Repeat, RotateCw, Package, Timer, CreditCard, Heart,
  CalendarPlus, Users, Barcode,
  ArrowLeftRight, ListTree, Calendar, Hash, RefreshCcw, Clock,
  Sigma, Calculator as CalcIcon, Globe2,
  UserCheck, Star as StarIcon, CalendarRange, Clock4, BadgeDollarSign, GraduationCap,
  FileWarning, PhoneCall, PartyPopper,
  MessagesSquare, ClipboardList, HelpCircle, ListChecks, Map,
  Reply, TrendingDown, Footprints,
  Sparkles, Inbox, Banknote, ShieldCheck as ShieldCheck2, Percent, BookOpen, LineChart as LineChart2, Receipt,
  HandCoins, GitBranch, Scale,
  TableProperties, Sheet, Send,
  History, Flame, Funnel,
  TestTube, PiggyBank, TrendingUp as TrendingUp2,
  FileBarChart,
  // Eksklüziv funksiyalar üçün əlavə ikonlar
  Building2, Volume2, Crown, Layers,
} from "lucide-react";

export type LabCategory =
  | "12hedef"
  | "ekstra10"
  | "pre1k"
  | "enterprise60"
  | "tamfunksional"
  | "exkluziv";

export type LabStatus = "preview" | "aktiv" | "alfa" | "tam";

export type LabFeature = {
  id: string;
  ad: string;
  tesvir: string;
  icon: LucideIcon;
  /** Rəng — gradient seçimi üçün */
  reng: "indigo" | "purple" | "rose" | "amber" | "emerald" | "cyan" | "sky" | "violet" | "pink" | "orange" | "teal" | "lime" | "slate" | "yellow";
  /** Hansı kateqoriyalara aiddir — bir funksiya bir neçə kateqoriyada görünə bilər */
  kateqoriyalar: LabCategory[];
  /** Tam funksional işləyirmi yoxsa preview-dir */
  status: LabStatus;
  /** Sandbox tipi — generic vs custom sandbox komponent */
  sandbox?: "generic" | "currency_fx" | "roi_calc" | "nps_survey" | "abc_pareto" | "eoq" | "ocr_receipt" | "ab_test" | "cohort" | "kpi_heatmap" | "executive_summary" | "trend_forecast";
  /** Funksiyanın əhəmiyyəti — preview qutusunda göstərilir */
  faydasi?: string[];
};

export const LAB_FEATURES: LabFeature[] = [
  // ============== İl-də 12 hədəf ==============
  {
    id: "multi-currency-fx",
    ad: "Multi-Currency və Real-time FX",
    tesvir: "Hər əməliyyat USD/EUR/RUB/AZN-də qeyd edilir. Markup, bank API alən analiz, kursla auto-convert. Hedge fond səviyyə.",
    icon: Coins, reng: "amber",
    kateqoriyalar: ["12hedef", "tamfunksional"],
    status: "tam",
    sandbox: "currency_fx",
    faydasi: ["Multi-valyuta hesabatı", "Real-time AZN konvertasiyası", "Forward kurs"],
  },
  {
    id: "workflow-designer",
    ad: "Workflow Designer (Visual)",
    tesvir: "Drag & drop ilə hər biznes prosesini qurma. Hər mərhələ kimə getsin, deadline neçə saat. Bottleneck identifkasiyası.",
    icon: Workflow, reng: "indigo",
    kateqoriyalar: ["12hedef"],
    status: "preview",
  },
  {
    id: "smart-notif-hub",
    ad: "Smart Notification Hub",
    tesvir: "Hər istifadəçi öz bildirişlərini özünə-uyğunlaşdırır (Telegram/WA, Slack, Digest düymlü, hover snooze 1 saat).",
    icon: Bell, reng: "rose",
    kateqoriyalar: ["12hedef", "tamfunksional"],
    status: "tam",
    sandbox: "generic",
  },
  {
    id: "customer-portal",
    ad: "Customer Self-Service Portal",
    tesvir: "Müştəri öz hesabı açır, sifariş tarixçəsi, borc, zəmanət, faktura PDF endirir.",
    icon: UserCircle, reng: "cyan",
    kateqoriyalar: ["12hedef"],
    status: "preview",
  },
  {
    id: "okr-kpi",
    ad: "OKR & KPI Tracker",
    tesvir: "Aylıq hədəflər, satış, marketlər, hər şəxs OKR. Real-time chart. Avtomatik analiz, hovuz adaptasiya.",
    icon: Target, reng: "emerald",
    kateqoriyalar: ["12hedef"],
    status: "preview",
  },
  {
    id: "b2b-portal",
    ad: "B2B Portal (topdan)",
    tesvir: "Topdan müştərilər öz qiymət siyahısını görür. Online sifariş, qaime, branding (öz logo).",
    icon: Briefcase, reng: "violet",
    kateqoriyalar: ["12hedef"],
    status: "preview",
  },
  {
    id: "smart-inventory-ml",
    ad: "Smart Inventory Forecasting (ML)",
    tesvir: "Mövsümünüu öyrənir (Yeni il, mərasim). Promo təsiri. Lead time. Reorder point dinamik.",
    icon: Boxes, reng: "sky",
    kateqoriyalar: ["12hedef"],
    status: "preview",
  },
  {
    id: "ai-agent",
    ad: "AI Agent (Otonom action)",
    tesvir: "Bu ay 10K AZN sapen — AI özü qiymət optimallaşdırır, kampaniyaya təklif edir. Voice command, Telegram bot.",
    icon: Bot, reng: "purple",
    kateqoriyalar: ["12hedef"],
    status: "preview",
  },
  {
    id: "api-marketplace",
    ad: "API Marketplace + Zapier",
    tesvir: "30+ hazır integraviya (Stripe, Shopify, Wolt, Azon İmza). Trigger→Action redaktor. OAuth 2.0.",
    icon: Plug, reng: "indigo",
    kateqoriyalar: ["12hedef"],
    status: "preview",
  },
  {
    id: "live-dashboards",
    ad: "Live Dashboards & Public Reports",
    tesvir: "Public link ilə dashboard paylaş. TV ekrana (mağaza divarı). Embed widget. Scheduled email reports.",
    icon: LineChart, reng: "cyan",
    kateqoriyalar: ["12hedef"],
    status: "preview",
  },
  {
    id: "compliance-center",
    ad: "Compliance Center",
    tesvir: "AZ qanunu uyğunluq auto-yoxlama e-qaime, KKM, UTQS, ÜDFR audit izi. Data export.",
    icon: ShieldCheck, reng: "emerald",
    kateqoriyalar: ["12hedef", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "sso-2fa",
    ad: "SSO + 2FA + Session Manager",
    tesvir: "Google/Apple ilə daxil ol. Hardware key (YubiKey). Hansı qurğudan giriş — istənilən qurğuyu logout.",
    icon: KeyRound, reng: "slate",
    kateqoriyalar: ["12hedef"],
    status: "preview",
  },

  // ============== Ekstra 10 ==============
  {
    id: "predictive-cashflow",
    ad: "Predictive Cashflow Calendar",
    tesvir: "30 gün üçün pul axını proqnozu. Hər gün üçün ehtimal: best/worst/average case.",
    icon: CalendarClock, reng: "pink",
    kateqoriyalar: ["ekstra10", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "loyalty-engine",
    ad: "Loyalty & Rewards Engine",
    tesvir: "Müştərilər üçün ad günü/Silver/Gold/Platinum/VIP, hər səviyyə üçün endirim. Avto-kampaniya.",
    icon: Trophy, reng: "amber",
    kateqoriyalar: ["ekstra10"],
    status: "preview",
  },
  {
    id: "sales-leaderboard",
    ad: "Sales Leaderboard (Gamification)",
    tesvir: "Satıcılar arasında reytinq, medallar (1, 2, 3 yer). Aylıq mükafat.",
    icon: Award, reng: "yellow",
    kateqoriyalar: ["ekstra10"],
    status: "preview",
  },
  {
    id: "voice-commands",
    ad: "Voice Commands",
    tesvir: "Hey Claude, AirPods doluna verib? — AI cavab verir. Mikrofon ilə danış, transkrip ə, action.",
    icon: Mic, reng: "purple",
    kateqoriyalar: ["ekstra10"],
    status: "preview",
  },
  {
    id: "ocr-receipt",
    ad: "Receipt Scanner (OCR)",
    tesvir: "Çəkdir qaiməni — sistem avtomatik oxuyur (parsi-mehsul, qiymət, tarix, satıcı).",
    icon: ScanLine, reng: "cyan",
    kateqoriyalar: ["ekstra10", "tamfunksional"],
    status: "tam", sandbox: "ocr_receipt",
  },
  {
    id: "smart-pricing",
    ad: "Smart Pricing Calculator",
    tesvir: "Markeplace komissiyasına görə avto qiymət — rəqib 5%, kargo, vergi, mənzu kdv.",
    icon: Calculator, reng: "emerald",
    kateqoriyalar: ["ekstra10", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "multi-language",
    ad: "Multi-language Support",
    tesvir: "AZ/RU/EN/TR interface. Müştəri-mərkəzli seçim olsun. Avto tərcümə (mümkün hesab).",
    icon: Languages, reng: "indigo",
    kateqoriyalar: ["ekstra10"],
    status: "preview",
  },
  {
    id: "anti-fraud",
    ad: "Anti-Fraud Detection",
    tesvir: "Sübhəli əməliyyat ISO%-i andırır (24 saat dinanda qoaytarma, məçuri vəsait).",
    icon: ShieldAlert, reng: "rose",
    kateqoriyalar: ["ekstra10"],
    status: "preview",
  },
  {
    id: "cohort-analysis",
    ad: "Cohort Analysis",
    tesvir: "Yyn yyn olub-mistarilərin 6 ay sonra hala olur. Retention rate matrix.",
    icon: BarChart3, reng: "violet",
    kateqoriyalar: ["ekstra10", "tamfunksional"],
    status: "tam", sandbox: "cohort",
  },
  {
    id: "selfie-attendance",
    ad: "Selfie Attendance",
    tesvir: "İşçi mağazaya gəlir, selfie ilə daxiimiyya yaranır. Geo-location yoxlama. Saxta gəliş qarşı.",
    icon: Camera, reng: "pink",
    kateqoriyalar: ["ekstra10"],
    status: "preview",
  },
  {
    id: "email-marketing",
    ad: "Email Marketing kampaniyası",
    tesvir: "Müştərilərə toplu email gönder. Open rate, click rate analitika. Şablon redaktor.",
    icon: Mail, reng: "sky",
    kateqoriyalar: ["ekstra10"],
    status: "preview",
  },
  {
    id: "whatsapp-bulk",
    ad: "WhatsApp toplu göndərmə",
    tesvir: "Seçilmiş seqmentə WA mesaj göndər. Şablon hazırla, dəyişənlər (ad), tarix planlaşdır.",
    icon: MessageSquare, reng: "emerald",
    kateqoriyalar: ["ekstra10"],
    status: "preview",
  },

  // ============== Pre 1K ==============
  {
    id: "birthday-msg",
    ad: "Doğum günü avto-mesaj",
    tesvir: "Müştəri doğum gününə avto WA təbrik + 10% endirim koduna. Avto kampaniya.",
    icon: Cake, reng: "pink",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "abandoned-cart",
    ad: "Tərk edilmiş səbət xatırlatma",
    tesvir: "Şarsana məhsul (təmamlanmış 24 saat sonra) anto-xatırlatma Markitə.",
    icon: ShoppingBag, reng: "amber",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "referral-program",
    ad: "Referral program",
    tesvir: "Müştəri öz kodunu paylaşır → yeni müştəri gətirir, hər ikisinə bonus. Tracking.",
    icon: UserPlus, reng: "emerald",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "review-system",
    ad: "Rəy toplama sistemi",
    tesvir: "Satışdan 3 gün sonra avto sorğu, NPS həvalandırılır.",
    icon: Star, reng: "yellow",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "coupon-system",
    ad: "Coupon (kupon) sistemi",
    tesvir: "Endirim kodu yarat. Faiz/məbləğ/məhsul-spesifik. Min səbət, son tarix, istifadə limiti.",
    icon: Ticket, reng: "rose",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "upsell",
    ad: "Upsell təklifi (cross-sell)",
    tesvir: "Satışda AI önərir: bu məhsulla ən çox alanlar A-tipi. POS-da \"birlikdə təklif et\".",
    icon: ArrowUpRight, reng: "violet",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "season-alert",
    ad: "Mövsüm xəbərdarlığı",
    tesvir: "Hava A, mərasim, Norruz və s. öncə hava məhsulları çıxar — AI mərasimə uyğun planlama.",
    icon: CloudSun, reng: "sky",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "influencer-track",
    ad: "Influencer/SMM track",
    tesvir: "Hər ucalan-edici UTM kodu, satışa təsiri. ROI hesablama.",
    icon: Megaphone, reng: "purple",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "demand-forecast",
    ad: "Tələb proqnozu (ML)",
    tesvir: "Hər məhsul üçün 7 günlük satış proqnozu. Tendensiya, mövsümselik aşkarlama.",
    icon: TrendingUp, reng: "indigo",
    kateqoriyalar: ["pre1k", "tamfunksional"],
    status: "tam", sandbox: "trend_forecast",
  },
  {
    id: "shift-planner",
    ad: "Növbə planlayıcı",
    tesvir: "İşçi növbə təşkili. Optimal yaq hesab edə bilər drag & drop ilə.",
    icon: CalendarDays, reng: "amber",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "expense-anomaly",
    ad: "Xərc anomaliyası (z-score)",
    tesvir: "Standart kənarlaşma 2σ aşan büyük xərclər — anomaliya. Şübhəli xərc, korruptsa.",
    icon: AlertTriangle, reng: "rose",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "competitor-radar",
    ad: "Rəqib radar",
    tesvir: "Rəqib instagram, websyt-də qiymət dəyişikliyini auto-tutub xəbər ver. Web scraping.",
    icon: Radar, reng: "rose",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "supplier-rating",
    ad: "Tədarükçü reytinqi",
    tesvir: "Hər tədarükçüyə üzrə anto-skor (vaxt, qiymət, defekt). Gold/Silver/Bronze nişanı.",
    icon: Truck, reng: "amber",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "cash-diff",
    ad: "Kassa fərqi yoxlama",
    tesvir: "Açılış + nağd qalığı + ödənişlər = günsonu. Real qalıq deyilsa, fərq raportu.",
    icon: Wallet, reng: "emerald",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "quick-doc",
    ad: "Tez sənəd (1-klik)",
    tesvir: "Tarixin qaldırılmasına 1-klikli sürətli satış konfiquraciya etmək.",
    icon: FileText, reng: "violet",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "whatsapp-orders",
    ad: "WhatsApp sifarişlər",
    tesvir: "WA-dan gələn mesaj → avto sifariş yaranır. AI mesajdan məhsulu çıxarır.",
    icon: MessageCircle, reng: "emerald",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "dynamic-pricing",
    ad: "Dynamic Pricing Engine",
    tesvir: "Satış qrupu bazasında qiymət yenidən qoy +10%, -10%, +5%. Stoka görə dəyişir.",
    icon: DollarSign, reng: "amber",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "auction",
    ad: "Auction (hərrac)",
    tesvir: "Stokda qalmış məhsulu auction-a qoy. Müştərilər online artırırlar.",
    icon: Gavel, reng: "rose",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "subscription-billing",
    ad: "Subscription billing",
    tesvir: "Aylıq/illik abonelik. Avto-faktura, avto-yeniləmə, churn analizi.",
    icon: Repeat, reng: "violet",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "recurring-orders",
    ad: "Recurring orders",
    tesvir: "Hər ayın 1-də avto-sifariş. Müştəri bir dəfə qurar, sonra avto-təkrarlanır.",
    icon: RotateCw, reng: "indigo",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "bundle",
    ad: "Bundle / paket məhsul",
    tesvir: "Ad ləçi bir neçə məhsuldan ibarət paket. Paket təklif yarat (Phone+kabel+kalif).",
    icon: Package, reng: "amber",
    kateqoriyalar: ["pre1k", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "flash-sale",
    ad: "Flash sale countdown",
    tesvir: "Konkret saatda 30% endirim. Geri sayım kampaniya. POS-da xəbərdar.",
    icon: Timer, reng: "rose",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "layaway",
    ad: "Layaway / taksit plan",
    tesvir: "Müştəri bir məhsulu rezerv edir. Hissə-hissə ödəyir, sonda alır.",
    icon: CreditCard, reng: "sky",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "wishlist",
    ad: "Wishlist / arzu siyahısı",
    tesvir: "Müştəri sevdiyi məhsulu wishlist-ə qoyur. Endirim olanda avto-bildiriş.",
    icon: Heart, reng: "pink",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "pre-order",
    ad: "Pre-order (öncədən sifariş)",
    tesvir: "Hələ stokda olmayan məhsul üçün öncədən qəbul et + avans al.",
    icon: CalendarPlus, reng: "indigo",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "group-buying",
    ad: "Group buying",
    tesvir: "10+ nəfər birlikdə alsa = 25% endirim. Sosial paylaşma motivasiyası.",
    icon: Users, reng: "emerald",
    kateqoriyalar: ["pre1k"],
    status: "preview",
  },
  {
    id: "barcode-batch",
    ad: "Barcode batch generator",
    tesvir: "Tək kliklə 500 unique EAN-13 barkod yarad — diqut hd, PDF.",
    icon: Barcode, reng: "slate",
    kateqoriyalar: ["pre1k", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },

  // ============== Enterprise-60 ==============
  {
    id: "multi-warehouse",
    ad: "Multi-warehouse transfer",
    tesvir: "Filiallar arası sürətli stok transferi. AI hansı filialın çatınmasını anlayır təklif edir.",
    icon: ArrowLeftRight, reng: "cyan",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "stock-escalation",
    ad: "Stok eskalasiya zənciri",
    tesvir: "Stok bitsə anbardara → 2 saat cavab yoxsa → menecere → 1 gün → sahibkara.",
    icon: ListTree, reng: "amber",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "expiry-track",
    ad: "Expiry date tracker",
    tesvir: "Bitirə, dərman üçün son istifadə tarixi. 90 günə öncə xəbərdarlıq, kampaniya.",
    icon: Calendar, reng: "rose",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "serial-imei",
    ad: "Serial/IMEI tracking",
    tesvir: "Hər unique serial üçün tarix kim aldı, kim sübdü, ne vaxt, zəmanət vəziyyəti.",
    icon: Hash, reng: "slate",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "returns-prediction",
    ad: "Returns prediction",
    tesvir: "AT keçmiş datadan hansı məhsul qaytarılma proqnozlandı.",
    icon: RefreshCcw, reng: "amber",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "aging-report",
    ad: "Inventory aging report",
    tesvir: "Stok yaşı: 0-30, 31-60, 61-90, 91-180, 180+ gün. Dormicag stok dəyəri gösterir.",
    icon: Clock, reng: "violet",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "abc-pareto",
    ad: "ABC Analysis (Pareto)",
    tesvir: "Pareto: A=80% gəlir verir 20% məhsuldan. B=normal, C-cərh. Fokus alıştır.",
    icon: Sigma, reng: "indigo",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "abc_pareto",
  },
  {
    id: "eoq-calc",
    ad: "EOQ Calculator",
    tesvir: "Economic Order Quantity: optimal sifariş miqdarı (sayulama+xərc, saxlama xərclərinin minimum).",
    icon: CalcIcon, reng: "emerald",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "eoq",
  },
  {
    id: "dropshipping",
    ad: "Dropshipping integration",
    tesvir: "Səm stokda saxlamaq, müştəri sifarişi birbaşa tədarükçüdən göndərilir.",
    icon: Globe2, reng: "cyan",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "employee-onboarding",
    ad: "Employee onboarding",
    tesvir: "Yeni işçi üçün avto-checklist: latın, sənəd, hesab, mentor.",
    icon: UserCheck, reng: "emerald",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "perf-review-360",
    ad: "Performance Review 360°",
    tesvir: "İşçi, rəhbər, həmkar, müştəri qiymətləndirir. Anonim toplama.",
    icon: StarIcon, reng: "amber",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "vacation-cal",
    ad: "Vacation calendar",
    tesvir: "İllər və ya muvocudluğu ümumi tə? Konflikt qarşısı alır.",
    icon: CalendarRange, reng: "sky",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "time-tracking",
    ad: "Time tracking (clock-in/out)",
    tesvir: "İşçi gəlcə əmsalda qeyd. Geo-location yoxlama.",
    icon: Clock4, reng: "indigo",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "payroll-az",
    ad: "Payroll Calculator (AZ)",
    tesvir: "Brüt → DSMF, GMF, gəlir vergisi + sale maaş. AZ qanununa uyğun.",
    icon: BadgeDollarSign, reng: "emerald",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "training-tracker",
    ad: "Training tracker",
    tesvir: "İşçi keçdiyi təlimlər, sertifikatlar, hansı təlim lazımdır.",
    icon: GraduationCap, reng: "violet",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "doc-expiry",
    ad: "Sənəd vaxtı bitir",
    tesvir: "Pasport, sürücü vəsiqəsi, sahibkar VOEN — son tarixində 30 gün öncə xəbərdar.",
    icon: FileWarning, reng: "rose",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "emergency-contacts",
    ad: "Emergency contacts",
    tesvir: "Hər işçinin yaxın qohuma əlaqə telefonu. Təcili halda nüvə-əmin.",
    icon: PhoneCall, reng: "rose",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "birthday-hr",
    ad: "Birthday/anniversary HR",
    tesvir: "İşçi doğum günü, iş yıldönümü → sahibkara dahi-bildiriş, avto təbrik.",
    icon: PartyPopper, reng: "pink",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "anonymous-feedback",
    ad: "Anonymous feedback box",
    tesvir: "İşçi anonimşitaqyəcəyə əgət bilen, Sahibkar oxuyur amma kim olduğu bəlli olmaz.",
    icon: Inbox, reng: "slate",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "nps-survey",
    ad: "NPS Survey",
    tesvir: "Net Promoter Score: müştəri 0-10 verir. Promoter/Passive/Detractor analizi.",
    icon: ClipboardList, reng: "indigo",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "nps_survey",
  },
  {
    id: "live-chat",
    ad: "Live chat widget",
    tesvir: "Veb-saytda və müştəri ERP-mərkəzlər canlı söhbət. SahibarYoperator ERP-nin canlı pəncərə.",
    icon: MessagesSquare, reng: "cyan",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "faq-bot",
    ad: "FAQ Bot (AI)",
    tesvir: "Müştəri tez-tez soruşulan AI cavablandırır. Yorumsa rəhbərə öyrə 24/7 stask.",
    icon: HelpCircle, reng: "violet",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "complaint-tracker",
    ad: "Şikayət tracker",
    tesvir: "Müştəri şikayət açır, prioritet ver, şşöyə layik et, son.",
    icon: ListChecks, reng: "rose",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "journey-map",
    ad: "Customer Journey Map",
    tesvir: "İlk təmas → maraq → satış → webgit → təcrid → web-saytda → satış marketinler heç bir.",
    icon: Map, reng: "sky",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "win-back",
    ad: "Win-back kampaniya",
    tesvir: "90+ gün almayan müştərilərə fərdi endirim/mesaj ata.",
    icon: Reply, reng: "amber",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "clv-calc",
    ad: "CLV Calculator",
    tesvir: "Customer Lifetime Value: hər müştərinin gələcək 24 ay təxminə qatxn.",
    icon: TrendingDown, reng: "indigo",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "touchpoint-timeline",
    ad: "Touchpoint timeline",
    tesvir: "Bir müştəri ilə bütün təmaslar (çağ, mesaj, satış, qaytarma) bir taymlayna görsünüb.",
    icon: Footprints, reng: "sky",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "personalization",
    ad: "Personalization engine",
    tesvir: "Müştərinin alış tarixçəsinə görə fərdi məhsul tövsiyyəsi.",
    icon: Sparkles, reng: "purple",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "multi-channel-inbox",
    ad: "Multi-channel inbox",
    tesvir: "WA + Email + Instagram + Facebook + bir mzbox-da. Hər mesaj kontekstə bağlı.",
    icon: Inbox, reng: "indigo",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "bank-reconcile",
    ad: "Bank reconciliation",
    tesvir: "POS satışları ilə bank gəliri auto-eşləşdirmə. Çatışmama yaxalananda.",
    icon: Banknote, reng: "emerald",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "credit-limit",
    ad: "Credit limit manager",
    tesvir: "Hər müştəri/iş üçün nisyə limiti. Aşıraq POS-da kart ödənişi sövdə.",
    icon: ShieldCheck2, reng: "rose",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "late-fees",
    ad: "Late payment fees",
    tesvir: "Borc 30+ gün geclənisə avto-cərimə (məs. günü 0.05%) elavə.",
    icon: Percent, reng: "amber",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "multi-account",
    ad: "Multi-account ledger",
    tesvir: "Bir necə kassa, bank hesab, bu kassa hesabı — hamısında balanslı.",
    icon: BookOpen, reng: "slate",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "cashflow-advanced",
    ad: "Cash Flow Forecast (advanced)",
    tesvir: "12 ay cash flow + sceneri analizi (best/worst/average case).",
    icon: LineChart2, reng: "emerald",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "az-tax-calc",
    ad: "AZ Vergi kalkulyatoru",
    tesvir: "Sadələşdirilmiş (2%), mənfəət 20%, gəlir 14% — auto hesablama. ÜTQ deta.",
    icon: Receipt, reng: "amber",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "currency-hedge",
    ad: "Currency hedging",
    tesvir: "USD/EUR-da olan zaman kurs ssfartmalara qarşı. Forward contract simulasiya.",
    icon: HandCoins, reng: "violet",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "petty-cash",
    ad: "Petty cash management",
    tesvir: "Kişik nağd xərclər (kafe, taxi). Hər kassir tə-limt, foto-çek.",
    icon: PiggyBank, reng: "emerald",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "expense-approval",
    ad: "Expense approval chain",
    tesvir: "500+ AZN xərc → menecer təsdiqi, 5000+ → sahibkar təsdiqi. Avto routing.",
    icon: GitBranch, reng: "indigo",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "budget-vs-actual",
    ad: "Budget vs Actual",
    tesvir: "Hər kateqoriya üçün ay büdcəni qoy. Real ranı ilə müqayisəsi avto-pos.",
    icon: Scale, reng: "violet",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "generic",
  },
  {
    id: "custom-report",
    ad: "Custom Report Builder",
    tesvir: "Drag & drop ilə öz hesabatın qur: hansı sütun, qruplaşdırma, filter.",
    icon: TableProperties, reng: "indigo",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "excel-pivot",
    ad: "Excel Pivot in Browser",
    tesvir: "Excel pivot table kimi məcburi düz büncülmkə, JS əsasında, serverdə bütün dataya.",
    icon: Sheet, reng: "emerald",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "export-scheduler",
    ad: "Export scheduler",
    tesvir: "Hər birinci ayın günü hesabat auto-Excel + email gönder.",
    icon: Send, reng: "cyan",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "audit-trail",
    ad: "Audit Trail Timeline",
    tesvir: "Hər müştəri/menecu üçün hər dəyşiklikdə tarix (kim-nə vatx ne dəyişdirdi).",
    icon: History, reng: "slate",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "kpi-heatmap",
    ad: "KPI Heatmap",
    tesvir: "Həftə günü × saat heatmap — hər yanan saatın \"isti\" saatları.",
    icon: Flame, reng: "rose",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "kpi_heatmap",
  },
  {
    id: "goal-funnel",
    ad: "Goal Funnel",
    tesvir: "Müştəri → Ilkin → Aktiv → Təkrar plan. Hər mərhələdə düşmə % göstər.",
    icon: Funnel, reng: "indigo",
    kateqoriyalar: ["enterprise60"],
    status: "preview",
  },
  {
    id: "ab-test",
    ad: "A/B Test Framework",
    tesvir: "Variant A vs B (qiymət, başlıq, şəkil). Konversiya statistik müqayisə.",
    icon: TestTube, reng: "purple",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "ab_test",
  },
  {
    id: "roi-calc",
    ad: "ROI Calculator",
    tesvir: "Reklam, kampaniya investisiya gəlir = real qayıdış faizi. Payback dövrü.",
    icon: TrendingUp2, reng: "emerald",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "roi_calc",
  },
  {
    id: "trend-forecast",
    ad: "Trend Forecasting",
    tesvir: "Linear regression ilə 7 günlük satış proqnozu. Tendensiya əlçatılan.",
    icon: TrendingUp, reng: "indigo",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "trend_forecast",
  },
  {
    id: "executive-ai-summary",
    ad: "Executive AI Summary",
    tesvir: "Sahibkara 1 paraqraf bütün biznesin xülasəs: satış, mənfəət, borc, risk.",
    icon: FileBarChart, reng: "purple",
    kateqoriyalar: ["enterprise60", "tamfunksional"],
    status: "tam", sandbox: "executive_summary",
  },

  // ============== EKSKLÜZİV — Satış stimullaşdırıcı 20 funksiya ==============
  // Bunlar rəqiblərdə olmayan və ya çox bahadan satılan high-value funksiyalardır.
  // Hər biri konkret biznes ağrı nöqtəsini həll edir.

  {
    id: "whatsapp-ai-autoreply",
    ad: "WhatsApp AI Auto-Reply (24/7)",
    tesvir: "Müştəri «qiymət nədir?», «stokda varmı?», «sifariş hara çatdı?» yazır — AI öz başına cavablandırır. 70% sorğu insan müdaxiləsi olmadan həll olur.",
    icon: MessageCircle, reng: "emerald",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["24/7 cavab", "70% avtomatik həll", "İşçi yükü -50%", "Müştəri məmnuniyyəti +30%"],
  },
  {
    id: "voice-pos",
    ad: "Səs ilə POS satışı",
    tesvir: "«Satış əlavə et: 2 iPhone, 1 qulaqcıq, kart ilə» — POS əməliyyatı səs ilə yaradılır. Mağaza işçisi əli boş qalanda da satış aparır.",
    icon: Volume2, reng: "purple",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["3× sürət", "Əlsiz işləmə", "Yaşlı işçilər üçün asan", "Az xəta"],
  },
  {
    id: "ai-camera-product",
    ad: "AI Kamera ilə məhsul tanıma",
    tesvir: "Kameranı məhsula tut — barkodsuz da sistem tanıyır (Computer Vision). Sayım və POS-da işləyir. Barkod yaxşı oxunmayanda da məhsulu tapır.",
    icon: Camera, reng: "cyan",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["Barkodsuz tanıma", "Sayım 5× sürət", "Yaş məhsullar üçün ideal", "Şəkildən axtarış"],
  },
  {
    id: "loyalty-rfm-engine",
    ad: "Müştəri Sədaqət Engine (RFM + Tier)",
    tesvir: "Hər müştəri avto-segmentasiya: Bronze/Silver/Gold/VIP. RFM analizi əsasında. Auto-təklif (doğum günü, dönüş, VIP-bonus).",
    icon: Crown, reng: "amber",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["Müştəri saxlama +40%", "VIP-lərə avto-diqqət", "Geri qayıdış", "Çapraz satış"],
  },
  {
    id: "marketplace-multisync",
    ad: "Marketplace Multi-Sync",
    tesvir: "Trendyol, Wildberries, Wolt, Bolt, Yango, Tap.az — hamısı tək cədvəldən. Stok dəyişəndə hamısı eyni anda yenilənir. Sifariş bir-yerə tökülür.",
    icon: Globe2, reng: "indigo",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["Stok eyniləşməsi", "Tək sifariş kanalı", "Komissiya hesabı", "Manual iş -90%"],
  },
  {
    id: "smart-cash-forecast",
    ad: "Smart Pul Axını Proqnozu (90 gün)",
    tesvir: "Növbəti 90 günün pul axını AI əsasında. Borc ödənişləri, gözlənən gəlir, mövsümi satış. Likvidlik xəbərdarlığı — «yanvar 15-də 5K ₼ kəsiri olacaq».",
    icon: LineChart2, reng: "rose",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["Kəsir öncədən bilinir", "Bank krediti planlaşması", "Sahibkar rahat yatır", "Müflisləşmədən qoruma"],
  },
  {
    id: "anti-theft-cctv",
    ad: "Anti-Theft Kamera Anomalia",
    tesvir: "POS-da işçi şübhəli əməliyyat (çox endirim, gecə vaxtı, müştərisiz satış) — CCTV kadr avto-bağlanır. Audit üçün hazır sənəd.",
    icon: ShieldAlert, reng: "rose",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["İşçi oğurluğu aşkar", "Kadr arxivi", "Aylıq itki -3-5%", "Etiraflar"],
  },
  {
    id: "customer-ltv-cac",
    ad: "Müştəri Lifetime Value (LTV/CAC)",
    tesvir: "Hər müştərinin 12 ay sonra dəyəri. Marketing xərci geri ödəmə dövrü. Hansı kanal pul gətirir, hansı israfdır — birbaşa görünür.",
    icon: TrendingUp2, reng: "emerald",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["ROI marketinq", "Hansı müştəri dəyərli", "Reklam optimization", "Payback müddəti"],
  },
  {
    id: "local-wholesale-index",
    ad: "Yerli Topdan Bazar İndeksi",
    tesvir: "Sədərək, Yaşıl Bazar, Avtovağzal — hər kateqoriya üçün gündəlik topdan qiymət. Topdan satış edənlər indi rəqib qiymətini bilir.",
    icon: BadgeDollarSign, reng: "amber",
    kateqoriyalar: ["exkluziv"],
    status: "preview",
    faydasi: ["Bazar qiyməti şəffaflığı", "Marja optimallaşdırması", "Rəqabətdə öndə", "AZ özəlliyi"],
  },
  {
    id: "ai-receipt-ocr",
    ad: "AI Çek/Qaimə Skaneri (OCR)",
    tesvir: "Təçhizatçı qaiməsini foto ilə skan et — məhsul adı, miqdar, qiymət avto-tanınır, sistemə daxil olur. Əl ilə daxil etmə bitir.",
    icon: ScanLine, reng: "cyan",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview", sandbox: "ocr_receipt",
    faydasi: ["Manual giriş -95%", "Qaimə 30 san", "Səhv minimumlaşıb", "Arxivləşmə avto"],
  },
  {
    id: "az-tax-evhf",
    ad: "Azərbaycan Vergi / eVHF avto",
    tesvir: "Vergi xidməti API ilə eVHF, EÇVF, KKM çek avto-göndərmə. Hər satış vergi sənədinə dönür. Audit hazır.",
    icon: FileText, reng: "sky",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["Vergi avtomatik", "Audit hazır", "Cərimə qoruma", "AZ qanunvericilik"],
  },
  {
    id: "ai-merchandiser",
    ad: "AI Mərchandayzer (rəf optimallaşması)",
    tesvir: "Hər mağaza üçün AI rəfləri necə düzmək lazımdır deyir. Hansı məhsul göz səviyyəsində, hansı yan-yana qoymaqdan satış artır.",
    icon: Layers, reng: "violet",
    kateqoriyalar: ["exkluziv"],
    status: "preview",
    faydasi: ["Rəf satışı +15-25%", "Mövsümi düzəliş", "Kros-satış optim", "Real data əsaslı"],
  },
  {
    id: "smart-complaint",
    ad: "Smart Şikayət İdarəsi (AI)",
    tesvir: "Şikayət gəlir → AI əhval-ruhiyyəni təyin edir, prioritet verir, ən uyğun işçiyə yönləndirir. SLA timer + auto-eskalasiya.",
    icon: MessagesSquare, reng: "rose",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["Reaksiya 2× sürət", "SLA yerinə yetirilmə", "İtirilmiş müştəri -60%", "Audit log"],
  },
  {
    id: "credit-risk-score",
    ad: "Müştəri Kredit Risk Score",
    tesvir: "Hər müştərinin keçmiş ödəniş tarixi, gecikmə, borc miqdarı əsasında 0-100 kredit balı. Risk yüksəkdirsə nisyə-borc avto-blok.",
    icon: Scale, reng: "amber",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["Borc itkisi -70%", "Avto-qəbul/imtina", "Sahibkara qoruma", "Risk siqnalı"],
  },
  {
    id: "promo-engine",
    ad: "Promo Engine (vizual qaydalar)",
    tesvir: "«2 al 1 pulsuz», «Cuma 30%», «İlk müştəriyə −15%» — vizual builder. POS-da avto-tətbiq. A/B test ilə hansı işlədi öyrən.",
    icon: Ticket, reng: "pink",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["Kampaniya 2 dəqiqədə", "POS avto-tətbiq", "A/B ölçü", "ROI hesabı"],
  },
  {
    id: "social-scheduler",
    ad: "Sosial Media Avto-Poster",
    tesvir: "Instagram / Facebook / TikTok-a məhsul kataloqdan avto-post. AI mətn yazır, ən yaxşı saatda göndərir. Yeni məhsul = sosial post avto.",
    icon: Send, reng: "violet",
    kateqoriyalar: ["exkluziv"],
    status: "preview",
    faydasi: ["Marketinq avto", "AI mətn", "Optimal saat", "Müştəri cəlb avto"],
  },
  {
    id: "customer-invoice-portal",
    ad: "Müştəri Online Qaimə Portalı",
    tesvir: "Müştəri öz qaiməsini portaldan görsün, ödəsin (Kart, Hyper, m10). Sənəd yığımı asanlaşır, müştəri sahibkarı zəngləməyə bilməz.",
    icon: CreditCard, reng: "sky",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["Ödəniş 5× sürət", "B2B portal", "Sənəd avto", "Telefon zəngi -50%"],
  },
  {
    id: "driver-app-track",
    ad: "Sürücü App + GPS Track",
    tesvir: "Çatdırma şəxsi mobil app-la sifariş götürür, GPS izlənir, müştəriyə real-time link gəlir («Sürücü 5 dəq qalıb»). Geo-track tarix.",
    icon: Truck, reng: "orange",
    kateqoriyalar: ["exkluziv", "tamfunksional"],
    status: "preview",
    faydasi: ["GPS canlı", "Müştəri görür", "Sürücü performans", "Çatdırma optim"],
  },
  {
    id: "holding-consolidation",
    ad: "Holding Çoxlu Şirkət Konsolidasiya",
    tesvir: "Bir neçə şirkəti tək hesabatda birləşdirmək. Holdinq sahibləri üçün — hər şirkətin P&L + ümumi.",
    icon: Building2, reng: "indigo",
    kateqoriyalar: ["exkluziv"],
    status: "preview",
    faydasi: ["Holdinq səviyyə", "Inter-company eliminate", "Top-level P&L", "Vahid hesabat"],
  },
  {
    id: "ai-phone-assistant",
    ad: "AI Telefon Asistenti (Voice Agent)",
    tesvir: "Müştəri zəng vurur → AI cavab verir, məlumat verir, sifariş qəbul edir, lazım gəlsə insana keçirir. Çağrı mərkəzi əvəzedicisi.",
    icon: PhoneCall, reng: "purple",
    kateqoriyalar: ["exkluziv"],
    status: "preview",
    faydasi: ["24/7 zəng cavabı", "Sifariş telefondan", "İşçi yükü azalır", "Heç bir zəng itmir"],
  },
];

export const LAB_CATEGORIES: { id: LabCategory | "hamisi" | "aktiv" | "preview"; label: string }[] = [
  { id: "hamisi", label: "Hamısı" },
  { id: "aktiv", label: "Aktiv" },
  { id: "preview", label: "Preview" },
  { id: "exkluziv", label: "⭐ Eksklüziv" },
  { id: "12hedef", label: "İl 12 hədəfi" },
  { id: "ekstra10", label: "Ekstra 10" },
  { id: "pre1k", label: "Pre 1K" },
  { id: "enterprise60", label: "Enterprise-60" },
  { id: "tamfunksional", label: "Tam funksional" },
];

export function getFeatureById(id: string): LabFeature | undefined {
  return LAB_FEATURES.find((f) => f.id === id);
}

export const RENG_GRADIENT: Record<LabFeature["reng"], string> = {
  indigo: "from-indigo-500 to-violet-500",
  purple: "from-purple-500 to-fuchsia-500",
  rose: "from-rose-500 to-pink-500",
  amber: "from-amber-500 to-orange-500",
  emerald: "from-emerald-500 to-teal-500",
  cyan: "from-cyan-500 to-sky-500",
  sky: "from-sky-500 to-blue-500",
  violet: "from-violet-500 to-purple-500",
  pink: "from-pink-500 to-rose-500",
  orange: "from-orange-500 to-amber-500",
  teal: "from-teal-500 to-emerald-500",
  lime: "from-lime-500 to-green-500",
  slate: "from-slate-500 to-zinc-500",
  yellow: "from-yellow-400 to-amber-500",
};

export const RENG_BG: Record<LabFeature["reng"], string> = {
  indigo: "bg-indigo-500/10 text-indigo-500",
  purple: "bg-purple-500/10 text-purple-500",
  rose: "bg-rose-500/10 text-rose-500",
  amber: "bg-amber-500/10 text-amber-500",
  emerald: "bg-emerald-500/10 text-emerald-500",
  cyan: "bg-cyan-500/10 text-cyan-500",
  sky: "bg-sky-500/10 text-sky-500",
  violet: "bg-violet-500/10 text-violet-500",
  pink: "bg-pink-500/10 text-pink-500",
  orange: "bg-orange-500/10 text-orange-500",
  teal: "bg-teal-500/10 text-teal-500",
  lime: "bg-lime-500/10 text-lime-500",
  slate: "bg-slate-500/10 text-slate-500",
  yellow: "bg-yellow-500/10 text-yellow-500",
};
